require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SolicitudesController do

  # This should return the minimal set of attributes required to create a valid
  # Solicitud. As you add validations to Solicitud, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nombre" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolicitudesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all solicitudes as @solicitudes" do
      solicitud = Solicitud.create! valid_attributes
      get :index, {}, valid_session
      assigns(:solicitudes).should eq([solicitud])
    end
  end

  describe "GET show" do
    it "assigns the requested solicitud as @solicitud" do
      solicitud = Solicitud.create! valid_attributes
      get :show, {:id => solicitud.to_param}, valid_session
      assigns(:solicitud).should eq(solicitud)
    end
  end

  describe "GET new" do
    it "assigns a new solicitud as @solicitud" do
      get :new, {}, valid_session
      assigns(:solicitud).should be_a_new(Solicitud)
    end
  end

  describe "GET edit" do
    it "assigns the requested solicitud as @solicitud" do
      solicitud = Solicitud.create! valid_attributes
      get :edit, {:id => solicitud.to_param}, valid_session
      assigns(:solicitud).should eq(solicitud)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Solicitud" do
        expect {
          post :create, {:solicitud => valid_attributes}, valid_session
        }.to change(Solicitud, :count).by(1)
      end

      it "assigns a newly created solicitud as @solicitud" do
        post :create, {:solicitud => valid_attributes}, valid_session
        assigns(:solicitud).should be_a(Solicitud)
        assigns(:solicitud).should be_persisted
      end

      it "redirects to the created solicitud" do
        post :create, {:solicitud => valid_attributes}, valid_session
        response.should redirect_to(Solicitud.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solicitud as @solicitud" do
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitud.any_instance.stub(:save).and_return(false)
        post :create, {:solicitud => { "nombre" => "invalid value" }}, valid_session
        assigns(:solicitud).should be_a_new(Solicitud)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitud.any_instance.stub(:save).and_return(false)
        post :create, {:solicitud => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested solicitud" do
        solicitud = Solicitud.create! valid_attributes
        # Assuming there are no other solicitudes in the database, this
        # specifies that the Solicitud created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Solicitud.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => solicitud.to_param, :solicitud => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested solicitud as @solicitud" do
        solicitud = Solicitud.create! valid_attributes
        put :update, {:id => solicitud.to_param, :solicitud => valid_attributes}, valid_session
        assigns(:solicitud).should eq(solicitud)
      end

      it "redirects to the solicitud" do
        solicitud = Solicitud.create! valid_attributes
        put :update, {:id => solicitud.to_param, :solicitud => valid_attributes}, valid_session
        response.should redirect_to(solicitud)
      end
    end

    describe "with invalid params" do
      it "assigns the solicitud as @solicitud" do
        solicitud = Solicitud.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitud.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitud.to_param, :solicitud => { "nombre" => "invalid value" }}, valid_session
        assigns(:solicitud).should eq(solicitud)
      end

      it "re-renders the 'edit' template" do
        solicitud = Solicitud.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitud.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitud.to_param, :solicitud => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solicitud" do
      solicitud = Solicitud.create! valid_attributes
      expect {
        delete :destroy, {:id => solicitud.to_param}, valid_session
      }.to change(Solicitud, :count).by(-1)
    end

    it "redirects to the solicitudes list" do
      solicitud = Solicitud.create! valid_attributes
      delete :destroy, {:id => solicitud.to_param}, valid_session
      response.should redirect_to(solicitudes_url)
    end
  end

end
